apiVersion: v1
data:
  datasources.yml: |
    apiVersion: 1
    datasources:
        - access: proxy
          basicAuth: false
          editable: false
          isDefault: false
          jsonData:
            derivedFields:
                - datasourceUid: tempo
                  matcherRegex: (?:traceID|trace_id)=(\w+)
                  name: TraceID
                  url: $${__value.raw}
            maxLines: 1000
          name: Loki
          type: loki
          url: http://loki.loki.svc.cluster.local:3100
          version: 1
        - access: proxy
          basicAuth: false
          editable: false
          isDefault: true
          jsonData:
            disableMetricsLookup: false
            exemplarTraceIdDestinations:
                - datasourceUid: tempo
                  name: traceID
            httpMethod: POST
          name: Mimir
          type: prometheus
          url: http://mimir.mimir.svc.cluster.local/prometheus
          version: 1
        - access: browser
          basicAuth: false
          editable: false
          isDefault: false
          jsonData:
            tracesToLogs:
                datasourceUid: Loki
                tags:
                    - job
                    - instance
                    - pod
                    - namespace
          name: Tempo
          type: tempo
          uid: tempo
          url: http://tempo.tempo.svc.cluster.local/
          version: 1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: default