apiVersion: v1
kind: Service
metadata:
  labels:
    name: grafana-agent
  name: grafana-agent
  namespace: default
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: grafana-agent-http-metrics
    port: 80
    protocol: TCP
    targetPort: 80
  - name: grafana-agent-thrift-compact
    port: 6831
    protocol: UDP
    targetPort: 6831
  - name: grafana-agent-thrift-binary
    port: 6832
    protocol: UDP
    targetPort: 6832
  - name: grafana-agent-thrift-http
    port: 14268
    protocol: TCP
    targetPort: 14268
  - name: grafana-agent-thrift-grpc
    port: 14250
    protocol: TCP
    targetPort: 14250
  selector:
    name: grafana-agent
  sessionAffinity: None
  type: ClusterIP
