apiVersion: v1
kind: Service
metadata:
#  annotations:
#    kubectl.kubernetes.io/last-applied-configuration: |
#      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"name":"loki"},"name":"loki","namespace":"loki"},"spec":{"ports":[{"name":"loki-http-metrics","port":3100,"targetPort":3100}],"selector":{"name":"loki"}}}
  labels:
    name: loki
  name: loki
  namespace: loki
spec:
#  clusterIP: 10.43.5.106
#  clusterIPs:
#  - 10.43.5.106
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: loki-http-metrics
    port: 3100
    protocol: TCP
    targetPort: 3100
  selector:
    name: loki
  sessionAffinity: None
  type: ClusterIP
