apiVersion: v1
data:
  overrides.yaml: |
    overrides:
  tempo.yaml: |
    auth_enabled: false
    compactor:
        compaction:
            compacted_block_retention: 24h
    distributor:
        receivers:
            jaeger:
                protocols:
                    thrift_compact:
                        endpoint: 0.0.0.0:6831
            otlp:
                protocols:
                    grpc:
                        endpoint: 0.0.0.0:55680
    ingester: {}
    server:
        http_listen_port: 3200
    storage:
        trace:
            backend: local
            blocklist_poll: 30s
            local:
                path: /tmp/tempo/traces
            wal:
                path: /var/tempo/wal
kind: ConfigMap
metadata:
  name: tempo
  namespace: tempo
